# Generated by Django 2.2.3 on 2019-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190720_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availabily',
            field=models.CharField(blank=True, choices=[('S', 'In Stock'), ('0', 'Out Of Range')], max_length=1, null=True),
        ),
    ]
