# Generated by Django 2.2.3 on 2019-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
