# Generated by Django 2.2.3 on 2019-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
